on:
  push:
  workflow_dispatch:

name: Deploy - Production
run-name: "Deploy: Production - @${{ github.actor }}"

concurrency:
  group: Production
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read # For actions/checkout
      deployments: write # For updating deployment history
    environment:
      name: Production
      url: https://staging.com
    steps:

    - name: Checkout
      uses: actions/checkout@v4
